---
- name: "Converge"
  hosts: "all"
  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: "Copy something to test use of synchronize module"
      ansible.builtin.copy:
        src: "/etc/hosts"
        dest: "/tmp/hosts-from-controller"
        mode: 0700

    - name: "Include labocbz.install_pufferpanel"
      tags:
        - "labocbz.install_pufferpanel"
      vars:
        inv_install_pufferpanel_data_path: "{{ inv_install_pufferpanel_data_path }}"
        inv_install_pufferpanel_web_address: "{{ inv_install_pufferpanel_web_address }}"
        inv_install_pufferpanel_web_port: "{{ inv_install_pufferpanel_web_port }}"
        inv_install_pufferpanel_sftp_address: "{{ inv_install_pufferpanel_sftp_address }}"
        inv_install_pufferpanel_sftp_port: "{{ inv_install_pufferpanel_sftp_port }}"
        inv_install_pufferpanel_config_path: "{{ inv_install_pufferpanel_config_path }}"
      ansible.builtin.include_role:
        name: "labocbz.install_pufferpanel"
