---
- name: "Converge"
  hosts: "cicd-docker-dind"
  tasks:

    - name: "Include labocbz.install_pufferpanel"
      tags:
        - "labocbz.install_pufferpanel"
      vars:
        install_pufferpanel__container_name: "{{ inv_install_pufferpanel__container_name }}"
        install_pufferpanel__data_path: "{{ inv_install_pufferpanel__data_path }}"
        install_pufferpanel__web_address: "{{ inv_install_pufferpanel__web_address }}"
        install_pufferpanel__web_port: "{{ inv_install_pufferpanel__web_port }}"
        install_pufferpanel__sftp_address: "{{ inv_install_pufferpanel__sftp_address }}"
        install_pufferpanel__sftp_port: "{{ inv_install_pufferpanel__sftp_port }}"
        install_pufferpanel__config_path: "{{ inv_install_pufferpanel__config_path }}"
      ansible.builtin.include_role:
        name: "labocbz.install_pufferpanel"
